spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:./vpay;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: false
      settings:
        trace: false
