server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:./data/vpay;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: root
    password: vpay_root_123
  h2:
    console:
      enabled: false
      settings:
        trace: false
  web:
    resources:
      static-locations: classpath:/static/,file:./templates/
